<a href="https://colab.research.google.com/github/pyojung/AIpython/blob/main/240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def total_pricedef(fruit_dict, purchases):
    total_price = 0
    for fruit, quantity in purchases.items():
        if fruit in fruit_dict:
            total_price += fruit_dict[fruit] * quantity
    return total_price

num_fruits = int(input())
fruit_dict = {}
for _ in range(num_fruits):
    fruit, price = input().split()
    fruit_dict[fruit] = int(price)

num_purchases = int(input())
purchases = {}
for _ in range(num_purchases):
    fruit, quantity = input().split()
    purchases[fruit] = int(quantity)


total_price = total_pricedef(fruit_dict, purchases)
print(total_price)

4
딸기 100
바나나 50
사과 1000
오렌지 500
2
딸기 2
오렌지 3
1700


In [3]:
import numpy as np

array = np.arange(1, 10, 2)
print(array)

[1 3 5 7 9]


In [4]:
import numpy as np

array = np.ones((3, 4))
print(array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
import numpy as np

array = np.linspace(0, 1, 10)
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [6]:
A = np.array(
 [[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]]
)

In [7]:
print(A.shape)

(5, 5)


In [11]:
print(A[3,3])

19


In [22]:
print(A[0:2,0:2])

[[1 2]
 [6 7]]


In [23]:
print(A[3:5,3:5])

[[19 20]
 [24 25]]


In [17]:
print(A[:,0:2])

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [24]:
print(A[1:,-2:])

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [32]:
b = np.arange(1,37,1)
arr1

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33])

In [27]:
print(B.shape)
print(B.size)

(3, 4)
12
